[tox]
envlist =
    coverage_erase
    # When updating Python versions, use search-and-replace
    # against the entire list of of versions
    # to ensure consistency throughout this file.
    py{3.14, 3.13, 3.12, 3.11, 3.10}
    tutorial
    coverage_report
    lint
    docs
    links
    ty
    build


[testenv]
runner = uv-venv-lock-runner
with_dev = true
extras =
    standard
package = wheel
wheel_build_env = build_wheel
depends =
    py{3.14, 3.13, 3.12, 3.11, 3.10}: coverage_erase
commands = coverage run -m pytest {posargs}


[testenv:coverage_erase]
base_python = py3.10
package = skip
skip_install = true
commands = coverage erase


[testenv:coverage_report]
base_python = py3.10
package = skip
skip_install = true
depends =
    py{3.14, 3.13, 3.12, 3.11, 3.10}
    tutorial
commands_pre =
    # Ignore the exit code of `coverage combine`
    # (in case the reports are already combined).
    - coverage combine
commands =
    coverage xml
    coverage report --show-missing


[testenv:tutorial]
base_python = py3.10
depends = coverage_erase
uv_seed = true
allowlist_externals = sh
commands_pre =
    sh docs_src/quickstart/setup/block001.sh
commands = coverage run -m pytest docs_src {posargs}


[testenv:lint]
base_python = py3.10
package = skip
skip_install = true
commands = prek run --all-files

[testenv:docs]
base_python = py3.10
package = skip
skip_install = true
commands = mkdocs build --strict


[testenv:links]
base_python = py3.10
package = skip
skip_install = true
allowlist_externals = npm
commands_pre =
    npm ci --prefer-offline --no-audit --fund=false --ignore-scripts
    npm exec -- puppeteer browsers install chrome
commands =
    npm exec -- linkspector check -c .linkspector.yml


[testenv:ty]
# When the Python version is updated here,
# update the version used in the CI `Typecheck` job, too.
base_python = py3.10
package = skip
skip_install = true
commands = ty check --exit-zero-on-warning


[testenv:build]
base_python = py3.10
package = skip
skip_install = true
allowlist_externals = uv
commands = uv build
