import importlib
import shutil
import sys
from datetime import date
from pathlib import Path
from types import ModuleType

import pytest

from tests._data import latest
from universi import regenerate_dir_to_all_versions
from universi.structure import Version, VersionBundle, VersionChange
from universi.structure.enums import AlterEnumSubInstruction
from universi.structure.schemas import AlterSchemaSubInstruction
from universi.structure.versions import Version, VersionBundle, VersionChange

CURRENT_DIR = Path(__file__).parent


@pytest.fixture(autouse=True, scope="module")
def remove_generated_files():
    yield
    shutil.rmtree(CURRENT_DIR / "_data/unions", ignore_errors=True)
    shutil.rmtree(CURRENT_DIR / "_data/v2000_01_01", ignore_errors=True)
    shutil.rmtree(CURRENT_DIR / "_data/v2001_01_01", ignore_errors=True)
    shutil.rmtree(CURRENT_DIR / "_data/v2002_01_01", ignore_errors=True)
    shutil.rmtree("tests/_data/latest/another_temp1", ignore_errors=True)
    shutil.rmtree("tests/_data/latest/another_temp1", ignore_errors=True)
    for module_name in list(sys.modules):
        if module_name.startswith("tests._data.latest.another_temp1"):
            del sys.modules[module_name]


@pytest.fixture()
def _reload_autogenerated_modules(request: pytest.FixtureRequest):
    for module_name in tuple(sys.modules):
        if module_name.startswith("tests._data"):
            del sys.modules[module_name]

    importlib.reload(request.module)


def generate_test_version_packages(
    *instructions: AlterSchemaSubInstruction | AlterEnumSubInstruction,
    package: ModuleType = latest,
) -> tuple[ModuleType, ModuleType]:
    class SomeVersionChange(VersionChange):
        description = "..."
        instructions_to_migrate_to_previous_version = instructions

    regenerate_dir_to_all_versions(
        package,
        VersionBundle(
            Version(date(2001, 1, 1), SomeVersionChange),
            Version(date(2000, 1, 1)),
        ),
    )

    from tests._data import v2000_01_01, v2001_01_01

    return v2000_01_01, v2001_01_01
